### ISSUE TITLE
creating a todo app with reactjs

### ISSUE THREAD

**Issue by adarsh1219** [MTalhaofc/HacktoberFest-2024#13]
please assign me this .

**Comment by adarsh1219** [comment]
please  label it as hactoberfest.

**Comment by AkshitSalwan** [comment]
Kindly add hacktoberfest and hacktoberfest-accepted tag to the PR as it was a contribution towards it. I'll really appreciate it.

**Comment by MTalhaofc** [comment]
Done

**Comment by AkshitSalwan** [comment]
Thankyou :)

**Comment by Smriti-Prajapati** [comment]
Please assign this issue to me for Hactoberfest.
