### ISSUE TITLE
Python: Number Plate Recognition using EasyOCR

### ISSUE THREAD

**Issue by thechiranjeevvyas** [MTalhaofc/HacktoberFest-2024#34]
Hello @MTalhaofc ,
I would like to add a number plate recognition system using EasyOCR that extracts vehicle plate text from images and outputs it in readable format.
***
Assign me this under Hacktoberfest2024 label
***

**Comment by MTalhaofc** [comment]
Assigned you with the Labels. Best of Luck for Hacktober Fest - 2024.
Please Make a PR as soon as possible.

**Comment by thechiranjeevvyas** [comment]
I have forked the repo but its giving error while cloning
***
Error is : RPC failed , fatal early EOF , fatal fetch -pack invalid index output

Tried many methods still repo isnt getting cloned

Can you help in this?

**Comment by priyansh2313** [comment]
i would to get it done, could you assign me this issue under hactoberfest 24

**Comment by MTalhaofc** [comment]
> i would like to get it done, could you assign me this issue under hactoberfest 24

Assigned it to @priyansh2313 Go Ahead, make a PR By calling the issue.
