### ISSUE TITLE
Simple Expense Tracker

### ISSUE THREAD

**Issue by judiemosinabre** [MTalhaofc/HacktoberFest-2024#49]
Hi @MTalhaofc, 

I would like to work on a simple python project that lets user to view and add expense for them to track. I’d be happy to contribute to this repository as part of Hacktoberfest 2024. Please assign this task to me and attach the `Hacktoberfest label`.

**Comment by MTalhaofc** [comment]
Assigend you the Issue @judiemosinabre . Go Ahead and Make a PR.
