### ISSUE TITLE
Feat:Add hello world in different languages like javascript,cpp,c,python,kotlin.

### ISSUE THREAD

**Issue by AkshitSalwan** [MTalhaofc/HacktoberFest-2024#5]
Can add basic codes to print hello world in different languages , to make it easy for beginners to learn basic syntax of various languages.

**Comment by MTalhaofc** [comment]
Sure Go Ahead, Will approve your PR's

**Comment by AkshitSalwan** [comment]
Kindly add hacktoberfest and hacktoberfest-accepted tag to the PR as it was a contribution towards it. I'll really appreciate it.
