### ISSUE TITLE
Dijkstra's Algorithm

### ISSUE THREAD

**Issue by SjxSubham** [MTalhaofc/HacktoberFest-2024#69]
### Hello @MTalhaofc 

**Dijkstra's Algorithm finds the shortest path from a source node to all other nodes in a weighted graph. It iteratively selects the node with the smallest tentative distance, updates distances of its neighbors, and ensures the shortest paths are discovered. Widely used in network routing and navigation systems.**

Thank You,
Sjx...

**Comment by MTalhaofc** [comment]
Merged!! Don't forget to follow me on GITHUB AND STAR THIS REPO.

**Comment by SjxSubham** [comment]
## If You are also a contributor U can contribute to my [repo](https://github.com/SjxSubham/Leetcode)
