### ISSUE TITLE
Implementing Bubble & Insertion sort using Linked Lists.

### ISSUE THREAD

**Issue by jagadeesh42** [MTalhaofc/HacktoberFest-2024#78]
As an addition to the C functions existing in this Repo. I'm thinking to add the implementations of the Bubble & Insertion Sort using Linked lists. 
Could you please mark this issue as hacktoberfest 2024 and assign it to me @MTalhaofc, Thanks you!

**Comment by MTalhaofc** [comment]
Don't Forget to Follow me on Github and Star this Repo. ASSIGNED!!

**Comment by jagadeesh42** [comment]
Hi, @MTalhaofc ,

Thank you for accepting the Issue #78. For this implementation I have raised #100 Pull Request. Could you please review and merge this PR. 

And if possible could you also please add the labels and assign it to me. Thanks!!
