### ISSUE TITLE
Merge Sort In Java

### ISSUE THREAD

**Issue by Shreya-Ghanty** [MTalhaofc/HacktoberFest-2024#88]
Hello @MTalhaofc

Merge Sort is a divide-and-conquer algorithm that sorts an array by recursively splitting it into halves, sorting each half, and merging them back together. It ensures a stable, time-efficient sort with a complexity of O(n log n). Ideal for large datasets.
Please assign me this issue under hacktoberfest-accepted and hacktoberfest tag
Thank you,
Shreya

**Comment by MTalhaofc** [comment]
Don't Forget to Follow me on Github and Star this Repo. MERGED!!
