### ISSUE TITLE
Letter Combinations of a Phone Number

### ISSUE THREAD

**Issue by Kirti-Pant** [MTalhaofc/HacktoberFest-2024#92]
I'm thinking to solve this DSA question as a new issue can you please assign me?
Description: Given a string containing digits from 2-9, return all possible letter combinations that the number could represent.
Example: Input: "23" Output: ["ad","ae","af","bd","be","bf","cd","ce","cf"]

**Comment by MTalhaofc** [comment]
STAR THE REPO!! AND FOLLOW ASSIGNED!!

**Comment by Kirti-Pant** [comment]
@MTalhaofc , I've uploaded my PR kindly have a look

**Comment by Kirti-Pant** [comment]
@MTalhaofc  please merge my PR so that it can be successfully contribute in hacktoberfest 2024
