### ISSUE TITLE
Issue: Adding placeholder in Text Analyzer form

### ISSUE THREAD

**Issue by kadambaridane** [MTalhaofc/HacktoberFest-2024#99]
Hello @MTalhaofc ,

Adding placeholder in the form makes easy to fill the form. I can make it user-friendly.

Kindly assign me this issue for Hactoberfest 2024!

**Comment by MTalhaofc** [comment]
Star the Repo & Follow me on Github.

**Comment by MTalhaofc** [comment]
Assigned

**Comment by kadambaridane** [comment]
Thanks 😊

**Comment by MTalhaofc** [comment]
@kadambaridane Closing the issue as you didn't raise a PR. 
Don't forget to star the Repo and Follow me on Github
